steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['buid', '-t', 'gcr.io/winter-brand-426415-r7:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/winter-brand-426415-r7:$SHORT_SHA']